/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotel.ui;

import com.hotel.bl.YearlyAcList;
import com.hotel.bl.YearlyEntryManager;
import com.hotel.model.Yearly;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class AcYearlyPanel extends javax.swing.JPanel {

    /**
     * Creates new form AcYearlyPanel
     */
    int selectYear;
    Yearly yearTotal;
    YearlyEntryManager yearlyManager;
    List<YearlyAcList> showYearlyList;
    DefaultTableModel model;
    String selectedMonth;
    public AcYearlyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblYearlyAccount = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        netIncomelbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblYearTabular = new javax.swing.JTable();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        netIncomelbl2 = new javax.swing.JLabel();
        btnYearlyIncome = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        lblYearlyAccount.setFont(new java.awt.Font("Times New Roman", 0, 24));
        lblYearlyAccount.setText("Yearly Account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(lblYearlyAccount)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblYearlyAccount)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        netIncomelbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netIncomelbl1.setText("Choose year from below :");
        netIncomelbl1.setPreferredSize(new java.awt.Dimension(25, 15));

        tblYearTabular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {null, null}
            },
            new String [] {
                "Month", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblYearTabular);

        netIncomelbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netIncomelbl2.setText("Yearly Net Income :");
        netIncomelbl2.setPreferredSize(new java.awt.Dimension(25, 15));

        btnYearlyIncome.setText("Show yearly income");
        btnYearlyIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearlyIncomeActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(netIncomelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(netIncomelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(btnYearlyIncome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnsave)
                        .addGap(101, 101, 101)
                        .addComponent(btnClear)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netIncomelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnYearlyIncome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netIncomelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnClear))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnYearlyIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearlyIncomeActionPerformed
// TODO add your handling code here:
    selectYear = jYearChooser1.getYear();
    System.out.println("year detector....." + selectYear);
    Yearly yearly = new Yearly();
    yearly.setSelect_year("%" + String.valueOf(selectYear) + "%");

    model = (DefaultTableModel) tblYearTabular.getModel();
    try {
        yearlyManager = new YearlyEntryManager();
        yearTotal = yearlyManager.totalNewYearlyNetIncome(yearly);

        txtTotal.setText(String.valueOf(yearTotal.getYearly_net_income()));
        System.out.println("I am here....total===" + yearTotal.getYearly_net_income());

        showYearlyList = new ArrayList<YearlyAcList>();
        showYearlyList = yearlyManager.showNewYearlyNetIncome(yearly);
        for (int i = 0; i < showYearlyList.size(); i++) {

            YearlyAcList yearlyAcList = showYearlyList.get(i);
            if (model.findColumn("Month") == 0) {

                String monthDetector =yearlyAcList.getSelect_month();

                System.out.println("Month===" + monthDetector);
                if (monthDetector.equals("1")) {
                    selectedMonth ="January";
                } else if (monthDetector.equals("2")) {
                    selectedMonth = "February";
                } else if (monthDetector.equals("3")) {
                    selectedMonth = "March";
                } else if (monthDetector.equals("4")) {
                    selectedMonth = "April";
                } else if (monthDetector.equals("5")) {
                    selectedMonth = "May";
                } else if (monthDetector.equals("6")) {
                    selectedMonth = "June";
                } else if (monthDetector.equals("7")) {
                    selectedMonth = "July";
                } else if (monthDetector.equals("8")) {
                    selectedMonth = "August";
                } else if (monthDetector.equals("9")) {
                    selectedMonth = "September";
                } else if (monthDetector.equals("10")) {
                    selectedMonth = "October";
                } else if (monthDetector.equals("11")) {
                    selectedMonth = "November";
                } else if (monthDetector.equals("12")) {
                    selectedMonth = "December";
                }
                model.setValueAt(selectedMonth, i, 0);

            }
            if (model.findColumn("Amount") == 1) {

                model.setValueAt(yearlyAcList.getMonthly_net_income(), i, 1);

            }
          
            System.err.println("Testing..........show month" + selectedMonth);
            System.err.println("Testing..........show monthly Monthly net income" +yearlyAcList.getMonthly_net_income());

        }
    } catch (ClassNotFoundException ex) {
    } catch (InstantiationException ex) {
    } catch (IllegalAccessException ex) {
    } catch (SQLException ex) {
    }
}//GEN-LAST:event_btnYearlyIncomeActionPerformed

private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
// TODO add your handling code here:

    Yearly insertYearly = new Yearly();

    insertYearly.setSelect_year(String.valueOf(selectYear));
    insertYearly.setYearly_net_income(Double.valueOf(yearTotal.getYearly_net_income()));
    try {

        yearlyManager.insertNewYearly(insertYearly);
        txtTotal.setText(null);
        for (int i = 0; i < showYearlyList.size() - 1; i++) {
            model.removeRow(i);
            model.removeRow(0);
            model.removeRow(1);
        }
    } catch (SQLException ex) {
    } catch (ClassNotFoundException ex) {
    } catch (InstantiationException ex) {
    } catch (IllegalAccessException ex) {
    }
}//GEN-LAST:event_btnsaveActionPerformed

private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
// TODO add your handling code here:

    for (int i = 0; i < showYearlyList.size() - 1; i++) {
        model.removeRow(i);
        model.removeRow(0);
    }
    txtTotal.setText(null);
}//GEN-LAST:event_btnClearActionPerformed

private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtTotalActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnYearlyIncome;
    private javax.swing.JButton btnsave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lblYearlyAccount;
    private javax.swing.JLabel netIncomelbl1;
    private javax.swing.JLabel netIncomelbl2;
    private javax.swing.JTable tblYearTabular;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
